Traceback (most recent call last):
  File "/opt/anaconda3/envs/pythonbook/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/anaconda3/envs/pythonbook/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/envs/pythonbook/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/envs/pythonbook/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/envs/pythonbook/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/anaconda3/envs/pythonbook/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/envs/pythonbook/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/anaconda3/envs/pythonbook/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
import statistics
from numpy import sqrt, mean, std

df = pd.read_csv("https://raw.githubusercontent.com/ethanweed/pythonbook/main/Data/harpo.csv")

# create two new variables for the grades from each tutor's students
tutor1 = pd.DataFrame(df.loc[df['tutor'] == 'Anastasia']['grade'])
tutor2 = pd.DataFrame(df.loc[df['tutor'] == 'Bernadette']['grade'])

# find number of student grades for each tutor
n1 = len(tutor1)
n2 = len(tutor2)

# find mean student grade for each tutor
u1 = mean(tutor1['grade'])
u2 = mean(tutor2['grade'])

# find variance in students' grades for each tutor
s1 = var(tutor1['grade'])
s2 = var(tutor2['grade'])


# find pooled standard deviation (square root of weighted variation, 
# divided by total N, with a correction for bias of -2)

s = sqrt(((n1) * s1 + (n2) * s2) / (n1 + n2 - 2))

# calculate Cohen's d
d = (u1 - u2) / s
d
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-40-8d863ff96bb1>[0m in [0;36m<module>[0;34m[0m
[1;32m     18[0m [0;34m[0m[0m
[1;32m     19[0m [0;31m# find variance in students' grades for each tutor[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 20[0;31m [0ms1[0m [0;34m=[0m [0mvar[0m[0;34m([0m[0mtutor1[0m[0;34m[[0m[0;34m'grade'[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     21[0m [0ms2[0m [0;34m=[0m [0mvar[0m[0;34m([0m[0mtutor2[0m[0;34m[[0m[0;34m'grade'[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     22[0m [0;34m[0m[0m

[0;31mNameError[0m: name 'var' is not defined
NameError: name 'var' is not defined

