Traceback (most recent call last):
  File "/Users/ethan/opt/miniconda3/envs/pythonbook/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/ethan/opt/miniconda3/envs/pythonbook/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/ethan/opt/miniconda3/envs/pythonbook/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/ethan/opt/miniconda3/envs/pythonbook/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/ethan/opt/miniconda3/envs/pythonbook/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/ethan/opt/miniconda3/envs/pythonbook/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/ethan/opt/miniconda3/envs/pythonbook/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/ethan/opt/miniconda3/envs/pythonbook/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
import seaborn as sns
from os import chdir as cd

# load some data
pathin = '/Users/ethan/Documents/GitHub/pythonbook/Data/'
file = 'skewdata.csv'

cd(pathin)

df_skew = pd.read_csv(file)

# plot histograms of the data
ax = sns.displot(
        data = df_skew, x = "Values", col="Skew",
        binwidth=.02, height=3, facet_kws=dict(margin_titles=True),
)

# This is just for the purposes of putting this figure in this book. Feel free to ignore!
glue("skew_fig", ax, display=False)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [37][0m, in [0;36m<cell line: 20>[0;34m()[0m
[1;32m     14[0m ax [38;5;241m=[39m sns[38;5;241m.[39mdisplot(
[1;32m     15[0m         data [38;5;241m=[39m df_skew, x [38;5;241m=[39m [38;5;124m"[39m[38;5;124mValues[39m[38;5;124m"[39m, col[38;5;241m=[39m[38;5;124m"[39m[38;5;124mSkew[39m[38;5;124m"[39m,
[1;32m     16[0m         binwidth[38;5;241m=[39m[38;5;241m.02[39m, height[38;5;241m=[39m[38;5;241m3[39m, facet_kws[38;5;241m=[39m[38;5;28mdict[39m(margin_titles[38;5;241m=[39m[38;5;28;01mTrue[39;00m),
[1;32m     17[0m )
[1;32m     19[0m [38;5;66;03m# This is just for the purposes of putting this figure in this book. Feel free to ignore![39;00m
[0;32m---> 20[0m [43mglue[49m([38;5;124m"[39m[38;5;124mskew_fig[39m[38;5;124m"[39m, ax, display[38;5;241m=[39m[38;5;28;01mFalse[39;00m)

[0;31mNameError[0m: name 'glue' is not defined
NameError: name 'glue' is not defined

